<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
	<SupportUrl>https://aka.ms/dotnet/10.0/windowsdesktop-runtime-win-x64.exe</SupportUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscUtils" Version="0.16.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
  </ItemGroup>

	<!-- 発行時に lzfse.dll を除外する設定 -->
	<Target Name="ExcludeLzfse" AfterTargets="ComputeFilesToPublish">
		<ItemGroup>
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(FileName)' == 'lzfse'" />
		</ItemGroup>
	</Target>

</Project>
